name: Complex
on: push
jobs:
  ubuntujob:
    runs-on: ubuntu-latest
    steps:
    - run: date
  windowsjob:
     runs-on: windows-latest
     steps:
     - run: date
  macosjob: 
    runs-on: macos-latest
    steps:
    - run: date
  depends:
     needs: [ubuntujob,windowsjob,macosjob]
     runs-on: macos-latest
     steps:
     - run: date
