# This is a basic workflow to help you get started with Actions

name: ComplexWF

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  ubuntujob:
    runs-on: ubuntu-latest
    steps:
    - run: date
  windowsjob:
     runs-on: windows-latest
     steps:
     - run: date
  macosjob: 
    runs-on: macos-latest
    steps:
    - run: date
  depends:
     needs: [ubuntujob,windowsjob,macosjob]
     runs-on: macos-latest
     steps:
     - run: date
